#pragma once

// torch
#include <torch/nn/cloneable.h>
#include <torch/nn/functional.h>
#include <torch/nn/module.h>
#include <torch/nn/modules/common.h>
#include <torch/nn/modules/container/any.h>

// harp
#include "opacity_options.hpp"

namespace harp {

class MoleculeLineImpl : public torch::nn::Cloneable<MoleculeLineImpl> {
 public:
  //! data table coordinate axes
  //! (nwave,) (npres,) (ndeltemp,)
  torch::Tensor wavenumber, ln_pressure, temperature_anomaly;

  //! tabulated line + same-species continuum cross section [m^2/mol]
  //! (nwave, npres, ndeltemp, 1)
  torch::Tensor ln_sigma_cross;

  //! base temperature profile [K]
  //! (npres, 1)
  torch::Tensor temperature_base;

  //! options with which this `MoleculeLineImpl` was constructed
  OpacityOptions options;

  //! Constructor to initialize the layer
  MoleculeLineImpl() : options(OpacityOptionsImpl::create()) {}
  explicit MoleculeLineImpl(OpacityOptions const& options_);
  void reset() override;

  //! Get optical properties
  /*!
   * This function calculates the absorption x-section of the gas
   * based on the tabulated data generated by the MoleculeLine.
   *
   * \param conc mole concentration [mol/m^3], (ncol, nlyr, nspecies)
   *
   * \param kwargs arguments for opacity calculation, must contain:
   *        "pres": pressure [Pa], (ncol, nlyr)
   *        "temp": temperature [K], (ncol, nlyr)
   *
   * \return optical properties, (nwave, ncol, nlyr, nprop=1)
   */
  torch::Tensor forward(torch::Tensor conc,
                        std::map<std::string, torch::Tensor> const& kwargs);
};
TORCH_MODULE(MoleculeLine);

}  // namespace harp
