[build-system]
requires = ["setuptools", "wheel", "cmake", "numpy", "ninja", "torch>=2.7.0"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
before-build-linux = "yum install -y epel-release && yum install -y netcdf-devel"
